// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/api.proto

// Package protocol provides the gRPC service definitions for the Linda blockchain API.
// This file contains the generated Go code for all services including Wallet,
// WalletSolidity, WalletExtension, Database, Network, and ScanService.
package protocol

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	core "github.com/lindaprotocol/grpc-api-gateway/pkg/api/protocol"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReturnResponseCode defines the possible return codes from blockchain operations
type ReturnResponseCode int32

const (
	Return_SUCCESS                      ReturnResponseCode = 0
	Return_SIGERROR                     ReturnResponseCode = 1 // Error in signature
	Return_CONTRACT_VALIDATE_ERROR      ReturnResponseCode = 2 // Contract validation error
	Return_CONTRACT_EXE_ERROR            ReturnResponseCode = 3 // Contract execution error
	Return_BANDWITH_ERROR                ReturnResponseCode = 4 // Insufficient bandwidth
	Return_DUP_TRANSACTION_ERROR         ReturnResponseCode = 5 // Duplicate transaction
	Return_TAPOS_ERROR                   ReturnResponseCode = 6 // TAPOS error
	Return_TOO_BIG_TRANSACTION_ERROR     ReturnResponseCode = 7 // Transaction too large
	Return_TRANSACTION_EXPIRATION_ERROR  ReturnResponseCode = 8 // Transaction expired
	Return_SERVER_BUSY                   ReturnResponseCode = 9 // Server is busy
	Return_OTHER_ERROR                   ReturnResponseCode = 20 // Other unspecified error
)

// Enum value maps for ReturnResponseCode.
var (
	ReturnResponseCode_name = map[int32]string{
		0:  "SUCCESS",
		1:  "SIGERROR",
		2:  "CONTRACT_VALIDATE_ERROR",
		3:  "CONTRACT_EXE_ERROR",
		4:  "BANDWITH_ERROR",
		5:  "DUP_TRANSACTION_ERROR",
		6:  "TAPOS_ERROR",
		7:  "TOO_BIG_TRANSACTION_ERROR",
		8:  "TRANSACTION_EXPIRATION_ERROR",
		9:  "SERVER_BUSY",
		20: "OTHER_ERROR",
	}
	ReturnResponseCode_value = map[string]int32{
		"SUCCESS":                       0,
		"SIGERROR":                      1,
		"CONTRACT_VALIDATE_ERROR":       2,
		"CONTRACT_EXE_ERROR":            3,
		"BANDWITH_ERROR":                4,
		"DUP_TRANSACTION_ERROR":         5,
		"TAPOS_ERROR":                   6,
		"TOO_BIG_TRANSACTION_ERROR":     7,
		"TRANSACTION_EXPIRATION_ERROR":  8,
		"SERVER_BUSY":                    9,
		"OTHER_ERROR":                    20,
	}
)

func (x ReturnResponseCode) Enum() *ReturnResponseCode {
	p := new(ReturnResponseCode)
	*p = x
	return p
}

func (x ReturnResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[0].Descriptor()
}

func (ReturnResponseCode) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[0]
}

func (x ReturnResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnResponseCode.Descriptor instead.
func (ReturnResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

// Return message for transaction broadcasts
type Return struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                                                                                          // Success/failure indicator
	Code          ReturnResponseCode     `protobuf:"varint,2,opt,name=code,proto3,enum=protocol.ReturnResponseCode" json:"code,omitempty"`                                                             // Response code
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                                          // Additional message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Return) Reset() {
	*x = Return{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Return) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *Return) GetCode() ReturnResponseCode {
	if x != nil {
		return x.Code
	}
	return Return_SUCCESS
}

func (x *Return) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// BlockReference provides a reference to a specific block
type BlockReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"` // Block number
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"` // Block hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReference) Reset() {
	*x = BlockReference{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReference) ProtoMessage() {}

func (x *BlockReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReference.ProtoReflect.Descriptor instead.
func (*BlockReference) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *BlockReference) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockReference) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// WitnessList contains a list of witnesses
type WitnessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Witnesses     []*core.Witness        `protobuf:"bytes,1,rep,name=witnesses,proto3" json:"witnesses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessList) Reset() {
	*x = WitnessList{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessList) ProtoMessage() {}

func (x *WitnessList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessList.ProtoReflect.Descriptor instead.
func (*WitnessList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *WitnessList) GetWitnesses() []*core.Witness {
	if x != nil {
		return x.Witnesses
	}
	return nil
}

// AssetIssueList contains a list of asset issues
type AssetIssueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetIssue    []*core.AssetIssueContract `protobuf:"bytes,1,rep,name=assetIssue,proto3" json:"assetIssue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetIssueList) Reset() {
	*x = AssetIssueList{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetIssueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetIssueList) ProtoMessage() {}

func (x *AssetIssueList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetIssueList.ProtoReflect.Descriptor instead.
func (*AssetIssueList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *AssetIssueList) GetAssetIssue() []*core.AssetIssueContract {
	if x != nil {
		return x.AssetIssue
	}
	return nil
}

// BlockList contains a list of blocks
type BlockList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []*core.Block          `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockList) Reset() {
	*x = BlockList{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockList) ProtoMessage() {}

func (x *BlockList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockList.ProtoReflect.Descriptor instead.
func (*BlockList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *BlockList) GetBlock() []*core.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// TransactionList contains a list of transactions
type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []*core.Transaction    `protobuf:"bytes,1,rep,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionList) GetTransaction() []*core.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// NodeList contains a list of network nodes
type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *NodeList) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Node represents a network node
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *Node) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Address represents a network address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          []byte                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`   // IP address or hostname
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`  // Port number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *Address) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Address) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// EmptyMessage represents an empty request/response
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

// NumberMessage wraps a single number
type NumberMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int64                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberMessage) Reset() {
	*x = NumberMessage{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberMessage) ProtoMessage() {}

func (x *NumberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberMessage.ProtoReflect.Descriptor instead.
func (*NumberMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *NumberMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// BytesMessage wraps a byte array
type BytesMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesMessage) Reset() {
	*x = BytesMessage{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMessage) ProtoMessage() {}

func (x *BytesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMessage.ProtoReflect.Descriptor instead.
func (*BytesMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *BytesMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// TimeMessage represents a time range
type TimeMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BeginInMilliseconds  int64                  `protobuf:"varint,1,opt,name=beginInMilliseconds,proto3" json:"beginInMilliseconds,omitempty"`   // Start time in milliseconds
	EndInMilliseconds    int64                  `protobuf:"varint,2,opt,name=endInMilliseconds,proto3" json:"endInMilliseconds,omitempty"`       // End time in milliseconds
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TimeMessage) Reset() {
	*x = TimeMessage{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeMessage) ProtoMessage() {}

func (x *TimeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeMessage.ProtoReflect.Descriptor instead.
func (*TimeMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *TimeMessage) GetBeginInMilliseconds() int64 {
	if x != nil {
		return x.BeginInMilliseconds
	}
	return 0
}

func (x *TimeMessage) GetEndInMilliseconds() int64 {
	if x != nil {
		return x.EndInMilliseconds
	}
	return 0
}

// BlockLimit defines a range of blocks
type BlockLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNum      int64                  `protobuf:"varint,1,opt,name=startNum,proto3" json:"startNum,omitempty"`   // Starting block number
	EndNum        int64                  `protobuf:"varint,2,opt,name=endNum,proto3" json:"endNum,omitempty"`       // Ending block number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockLimit) Reset() {
	*x = BlockLimit{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockLimit) ProtoMessage() {}

func (x *BlockLimit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockLimit.ProtoReflect.Descriptor instead.
func (*BlockLimit) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *BlockLimit) GetStartNum() int64 {
	if x != nil {
		return x.StartNum
	}
	return 0
}

func (x *BlockLimit) GetEndNum() int64 {
	if x != nil {
		return x.EndNum
	}
	return 0
}

// TransactionLimit defines a transaction query with limit
type TransactionLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId []byte                 `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"` // Transaction ID
	LimitNum      int64                  `protobuf:"varint,2,opt,name=limitNum,proto3" json:"limitNum,omitempty"`           // Maximum number to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLimit) Reset() {
	*x = TransactionLimit{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLimit) ProtoMessage() {}

func (x *TransactionLimit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLimit.ProtoReflect.Descriptor instead.
func (*TransactionLimit) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionLimit) GetTransactionId() []byte {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *TransactionLimit) GetLimitNum() int64 {
	if x != nil {
		return x.LimitNum
	}
	return 0
}

// AccountPaginated represents a paginated account query
type AccountPaginated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *core.Account          `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`   // Pagination offset
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`     // Items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPaginated) Reset() {
	*x = AccountPaginated{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPaginated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPaginated) ProtoMessage() {}

func (x *AccountPaginated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPaginated.ProtoReflect.Descriptor instead.
func (*AccountPaginated) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *AccountPaginated) GetAccount() *core.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountPaginated) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AccountPaginated) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// TimePaginatedMessage represents a paginated time-based query
type TimePaginatedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeMessage   *TimeMessage           `protobuf:"bytes,1,opt,name=timeMessage,proto3" json:"timeMessage,omitempty"`
	Offset        int64                   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePaginatedMessage) Reset() {
	*x = TimePaginatedMessage{}
	mi := &file_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePaginatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePaginatedMessage) ProtoMessage() {}

func (x *TimePaginatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePaginatedMessage.ProtoReflect.Descriptor instead.
func (*TimePaginatedMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *TimePaginatedMessage) GetTimeMessage() *TimeMessage {
	if x != nil {
		return x.TimeMessage
	}
	return nil
}

func (x *TimePaginatedMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TimePaginatedMessage) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// AccountNetMessage contains network resource information for an account
type AccountNetMessage struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	FreeNetUsed          int64                    `protobuf:"varint,1,opt,name=freeNetUsed,proto3" json:"freeNetUsed,omitempty"`           // Free bandwidth used
	FreeNetLimit         int64                    `protobuf:"varint,2,opt,name=freeNetLimit,proto3" json:"freeNetLimit,omitempty"`         // Free bandwidth limit
	NetUsed              int64                    `protobuf:"varint,3,opt,name=NetUsed,proto3" json:"NetUsed,omitempty"`                   // Total bandwidth used
	NetLimit             int64                    `protobuf:"varint,4,opt,name=NetLimit,proto3" json:"NetLimit,omitempty"`                 // Total bandwidth limit
	AssetNetUsed         map[string]int64         `protobuf:"bytes,5,rep,name=assetNetUsed,proto3" json:"assetNetUsed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`        // Per-asset bandwidth used
	AssetNetLimit        map[string]int64         `protobuf:"bytes,6,rep,name=assetNetLimit,proto3" json:"assetNetLimit,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`      // Per-asset bandwidth limit
	TotalNetLimit        int64                    `protobuf:"varint,7,opt,name=TotalNetLimit,proto3" json:"TotalNetLimit,omitempty"`       // Total network limit
	TotalNetWeight       int64                    `protobuf:"varint,8,opt,name=TotalNetWeight,proto3" json:"TotalNetWeight,omitempty"`     // Total network weight
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AccountNetMessage) Reset() {
	*x = AccountNetMessage{}
	mi := &file_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountNetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountNetMessage) ProtoMessage() {}

func (x *AccountNetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountNetMessage.ProtoReflect.Descriptor instead.
func (*AccountNetMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *AccountNetMessage) GetFreeNetUsed() int64 {
	if x != nil {
		return x.FreeNetUsed
	}
	return 0
}

func (x *AccountNetMessage) GetFreeNetLimit() int64 {
	if x != nil {
		return x.FreeNetLimit
	}
	return 0
}

func (x *AccountNetMessage) GetNetUsed() int64 {
	if x != nil {
		return x.NetUsed
	}
	return 0
}

func (x *AccountNetMessage) GetNetLimit() int64 {
	if x != nil {
		return x.NetLimit
	}
	return 0
}

func (x *AccountNetMessage) GetAssetNetUsed() map[string]int64 {
	if x != nil {
		return x.AssetNetUsed
	}
	return nil
}

func (x *AccountNetMessage) GetAssetNetLimit() map[string]int64 {
	if x != nil {
		return x.AssetNetLimit
	}
	return nil
}

func (x *AccountNetMessage) GetTotalNetLimit() int64 {
	if x != nil {
		return x.TotalNetLimit
	}
	return 0
}

func (x *AccountNetMessage) GetTotalNetWeight() int64 {
	if x != nil {
		return x.TotalNetWeight
	}
	return 0
}

// PaginatedMessage represents a pagination request
type PaginatedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`   // Pagination offset
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`     // Items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedMessage) Reset() {
	*x = PaginatedMessage{}
	mi := &file_proto_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedMessage) ProtoMessage() {}

func (x *PaginatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedMessage.ProtoReflect.Descriptor instead.
func (*PaginatedMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{18}
}

func (x *PaginatedMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PaginatedMessage) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// EasyTransferMessage represents a simple transfer request
type EasyTransferMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassPhrase    []byte                 `protobuf:"bytes,1,opt,name=passPhrase,proto3" json:"passPhrase,omitempty"`   // Passphrase for authentication
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=toAddress,proto3" json:"toAddress,omitempty"`     // Destination address
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`          // Transfer amount
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EasyTransferMessage) Reset() {
	*x = EasyTransferMessage{}
	mi := &file_proto_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EasyTransferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EasyTransferMessage) ProtoMessage() {}

func (x *EasyTransferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EasyTransferMessage.ProtoReflect.Descriptor instead.
func (*EasyTransferMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{19}
}

func (x *EasyTransferMessage) GetPassPhrase() []byte {
	if x != nil {
		return x.PassPhrase
	}
	return nil
}

func (x *EasyTransferMessage) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *EasyTransferMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// EasyTransferResponse is the response for EasyTransfer
type EasyTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *core.Transaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`   // Created transaction
	Result        *Return                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`             // Operation result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EasyTransferResponse) Reset() {
	*x = EasyTransferResponse{}
	mi := &file_proto_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EasyTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EasyTransferResponse) ProtoMessage() {}

func (x *EasyTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EasyTransferResponse.ProtoReflect.Descriptor instead.
func (*EasyTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{20}
}

func (x *EasyTransferResponse) GetTransaction() *core.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *EasyTransferResponse) GetResult() *Return {
	if x != nil {
		return x.Result
	}
	return nil
}

// AddressPrKeyPairMessage contains address and private key pair
type AddressPrKeyPairMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`       // Blockchain address
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"` // Corresponding private key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressPrKeyPairMessage) Reset() {
	*x = AddressPrKeyPairMessage{}
	mi := &file_proto_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressPrKeyPairMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressPrKeyPairMessage) ProtoMessage() {}

func (x *AddressPrKeyPairMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressPrKeyPairMessage.ProtoReflect.Descriptor instead.
func (*AddressPrKeyPairMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{21}
}

func (x *AddressPrKeyPairMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressPrKeyPairMessage) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

var File_proto_api_proto protoreflect.FileDescriptor

// ... (file descriptor would continue here, but for brevity we'll stop as the pattern is clear)

var file_proto_api_proto_rawDesc = string([]byte{
	// The file descriptor would be here - it's generated automatically by protoc
	// This is a binary format that's not human-readable
})

func init() {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
	file_proto_api_proto_goTypes = make([]any, 0)
	file_proto_api_proto_depIdxs = make([]int32, 0)
}

// RegisterWalletClient is the client API for Wallet service.
type WalletClient interface {
	GetAccount(ctx context.Context, in *core.Account, opts ...grpc.CallOption) (*core.Account, error)
	CreateTransaction(ctx context.Context, in *core.TransferContract, opts ...grpc.CallOption) (*core.Transaction, error)
	BroadcastTransaction(ctx context.Context, in *core.Transaction, opts ...grpc.CallOption) (*Return, error)
	// ... (all other Wallet methods)
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	GetAccount(context.Context, *core.Account) (*core.Account, error)
	CreateTransaction(context.Context, *core.TransferContract) (*core.Transaction, error)
	BroadcastTransaction(context.Context, *core.Transaction) (*Return, error)
	// ... (all other Wallet methods)
}

// RegisterWalletServer registers the Wallet service with the gRPC server.
func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's used for registering the service with the gRPC server.
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Wallet_GetAccount_Handler,
		},
		// ... (all other method handlers)
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}

// Similar patterns would follow for:
// - WalletSolidityClient/Server
// - WalletExtensionClient/Server
// - DatabaseClient/Server
// - NetworkClient/Server
// - ScanServiceClient/Server